# Stable features
reorder_imports = true
reorder_modules = true

# Unstable features (nightly only)
unstable_features = true
force_multiline_blocks = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
